apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: giri-opa
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCy0IJnQlSRP0xG1Lg6+EKT7mmwcKuqqKInEnH39kTQzL1m9MsE3vI2fGcqvw5vGYeRRuleTaDbWhlmO5HlIl/3PtCZWmBwPkFFFErjIvk7uGU4rNbz6fuwuY51fmKMqMRGw6+kBYh1WQccSkIH760SEjBl1vpZba8oSSuV56qD8HszaOtB9mV0vqnzHWQ7LdjHs2qd8jgJabnTbAjQ30Ng+kZFVxgn7pavLNn+dXhLh1t6rnCZ4UgiKDRTBTR4JFGUvX+rHlRC8qABo4lHzbS41YqbZAtUB3BGkIHG0c4MtVO65tvPlLb19a0IEXm27kxRVh5A2ePx0hn/9eilEvaBJ8P41WwPgkqfP4xZKqFnssseuUJNZQjvPeGgRqcntzglvljXNYQHlr4SrYKe1IIn4je+uyawHB0=
  template:
    metadata:
      creationTimestamp: null
      name: giri-opa
      namespace: default

