apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: giri-feb
  namespace: default
spec:
  encryptedData:
    credentials.password: AQB8s4x+lcG04pMPJl27uMU6ow0Xv3AL33Qo34taUOMDvq34eND9DPPNGloUpenkwuQd/JhCMy18pPWLUU7+I0OyXaqaNQe0HSl//FoU6fQQngNpRGN5W+h43bBVK7e/x9TCi5tSCKO1SqA4cHmpGpGQCavs40rmBCFBjJJEIbs8k9o4ASBUVw1QEOhzGRt4wP/f6C96hvqILe0HNKbf0swgP7cx7O5rCKCX47OgzSHODvNtr5sjbB/Xotw6fZ9o8a93OzwR7F66TIEOYeNSOcbwocHD3fwP3zkaefRq/qbO61og1qKjexFgcT8L5CXvTKusJXya5DmF4m2sYRSkEQpBqwIGqPkKIas7xZUR9go5VMecQYlaNdq+bMISKl6tvksYRLYjJroDSTzNf2lNLd/M/Axb3KuVNLA=
  template:
    metadata:
      creationTimestamp: null
      name: giri-feb
      namespace: default

