apiVersion: apps.k8smgmt.io/v3
kind: Override
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: manifestsFile
  name: webapp1
  project: giri-may
spec:
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-feb24-qc
  resource:
    selector:
      name: workload-app
    type: Workload
  type: Yaml
  valuesPath:
    name: file://webapp1/webapp1.yaml
