apiVersion: infra.k8smgmt.io/v3
kind: AddonOverride
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: manifestsFile
  name: add-on-override
  project: giri-may
spec:
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-feb17
  resource:
    selector:
      name: addon-xwing
    type: Addon
  type: Yaml
  valuesPath:
    name: file://add-on-override/add-on-override.yaml
