apiVersion: security.k8smgmt.io/v3
kind: ClusterNetworkPolicyRule
metadata:
  name: new
  project: giri-may
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/new/cluster-wide.yaml
    options: {}
    type: Yaml
  sharing:
    enabled: true
    projects:
    - name: '*'
  version: v3
