apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp-custom
  project: giri-may
spec:
  base:
    name: bp-gold
    version: v1-gold
  componentsCriticality:
  - name: addon-xwing
  customAddons:
  - name: addon-xwing
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  type: custom
  version: v1-custom
  versionState: active
