apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp-custom
  project: giri-may
spec:
  base:
    name: default
    version: 3.2.0
  componentsCriticality:
  - name: addon-xwing
  customAddons:
  - name: addon-xwing
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: bp-default
  versionState: active
