apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  name: workload-ns
  project: giri-may
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-feb24-qc
    - key: rafay.dev/clusterName
      value: giri-mar3-mks1
  resourceQuotas:
    pods: "4"
